/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.shyam.avro.order;
@org.apache.avro.specific.AvroGenerated
public enum AddressType implements org.apache.avro.generic.GenericEnumSymbol<AddressType> {
  UNKNOWN, MAILING, BILLING  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"AddressType\",\"namespace\":\"com.shyam.avro.order\",\"symbols\":[\"UNKNOWN\",\"MAILING\",\"BILLING\"],\"default\":\"UNKNOWN\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
